theme: jekyll-theme-cayman

plugins:
  - jekyll-docs
#  - jekyll-redirect-from

timezone: 'America/New_York'
site.gaaccount: 'UA-140424942-1'

#permalink: /garbage
#redirect_to:
#  - https://raw.githubusercontent.com/mathieu-aubin/c7repos/master/c7repos.sh
